const {chromium}=require('C:/Users/sajin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/admin.html');await page.locator('#editor-form').waitFor({state:'visible'});const original=await (await page.request.get('http://127.0.0.1:8765/api/admin/content')).json();
 await page.getByLabel('Main headline',{exact:true}).fill('CMS browser test headline');await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('status').filter({hasText:'Saved.'}).waitFor();await page.goto('http://127.0.0.1:8765/');assert.equal(await page.locator('h1').textContent(),'CMS browser test headline');
 await page.goto('http://127.0.0.1:8765/admin.html');await page.locator('#editor-form').waitFor({state:'visible'});assert.equal(await page.getByLabel('Main headline',{exact:true}).inputValue(),'CMS browser test headline');
 await page.getByLabel('Replace with an uploaded photo').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aNxkAAAAASUVORK5CYII=','base64')});await page.getByRole('status').filter({hasText:'Photo uploaded.'}).waitFor();assert.ok((await page.getByLabel('Image URL',{exact:true}).inputValue()).startsWith('/media/'));await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('status').filter({hasText:'Saved.'}).waitFor();
 await page.getByRole('button',{name:'Service list',exact:true}).click();await page.getByRole('button',{name:'Add a service',exact:true}).click();assert.equal(await page.locator('.editor-item').count(),4);
 // Restore the real company content after checking persisted updates. No test copy is published.
 const current=await (await page.request.get('http://127.0.0.1:8765/api/admin/content')).json();const restore=await page.request.put('http://127.0.0.1:8765/api/admin/content',{headers:{Origin:'http://127.0.0.1:8765'},data:{content:original.content,revision:current.revision}});assert.equal(restore.status(),200);
 await page.reload();await page.locator('#editor-form').waitFor({state:'visible'});await page.getByRole('button',{name:'Privacy policy',exact:true}).click();assert.ok(await page.locator('textarea').inputValue());await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'qa/admin-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('CMS browser save, reload persistence, image upload, service addition and mobile editor checks passed; original content restored.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

