import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto,createHmac,createHash} from 'node:crypto';
import {validate,validateFiles} from '../server/validation.mjs';import {handle} from '../dist/server/index.js';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const id='d9e83a07-5f48-4a55-8592-80946879e999';
const fields={name:'Test Visitor',company:'=IMPORTXML("bad")',phone:'+971 50 123 4567',email:'test@example.com',location:'Dubai',service:'Building maintenance',description:'Site maintenance request',contactMethod:'Email',consent:'yes',requestId:id,website:''};
const candidate={name:'Test Candidate',phone:'+971501234567',email:'candidate@example.com',location:'Ajman',position:'Technician',experience:'3 years',qualifications:'Diploma',availability:'One month',consent:'yes',requestId:id};
const pdf=new File(['%PDF-1.7\nexample test fixture'], 'test.pdf',{type:'application/pdf'});
const env={GOOGLE_SCRIPT_URL:'https://script.google.com/macros/s/testing/exec',GOOGLE_BRIDGE_SECRET:'test-only-secret',TURNSTILE_SECRET_KEY:'test-only-key',TURNSTILE_SITE_KEY:'public-test-key'};
function formRequest(kind,extra={},file=null){const data=new FormData();for(const[k,v]of Object.entries({...kind==='inquiry'?fields:candidate,...extra}))data.append(k,v);data.append('turnstileToken','test-token');if(file)data.append('files',file);return new Request('https://tristone.example/api/'+(kind==='inquiry'?'inquiries':'applications'),{method:'POST',headers:{Origin:'https://tristone.example'},body:data});}
test('validates required fields, email, consent and service allowlist',()=>{assert.equal(validate(fields,'inquiry').name,'Test Visitor');for(const change of [{email:'bad'},{consent:'no'},{service:'unlisted'},{website:'bot'}])assert.throws(()=>validate({...fields,...change},'inquiry'));assert.equal(validate(candidate,'application').position,'Technician');});
test('requires CV and rejects disguised or oversized uploads',async()=>{await assert.rejects(validateFiles([],'application'));await assert.rejects(validateFiles([new File(['<script>bad</script>'],'fake.pdf')],'application'));await assert.rejects(validateFiles([new File(['%PDF-'+ 'x'.repeat(5*1024*1024)],'large.pdf')],'application'));assert.equal((await validateFiles([pdf],'application'))[0].mime,'application/pdf');});
test('unconfigured deployment fails closed without accepting data',async()=>{const response=await handle(formRequest('inquiry'),{});assert.equal(response.status,503);assert.equal((await response.json()).reference,undefined);});
test('rejects cross-origin requests and failed spam checks',async()=>{const request=formRequest('inquiry');const cross=new Request(request,{headers:{Origin:'https://attacker.example'}});assert.equal((await handle(cross,env)).status,403);assert.equal((await handle(formRequest('inquiry'),env,async()=>new Response(JSON.stringify({success:false})))).status,403);});
test('separate endpoints issue references only after storage confirms',async()=>{const seen=[];const fetcher=async(url,options)=>{if(String(url).includes('siteverify'))return Response.json({success:true,hostname:'tristone.example',action:seen.length?'application':'inquiry'});const envelope=JSON.parse(options.body);assert.equal(envelope.signature,createHmac('sha256',env.GOOGLE_BRIDGE_SECRET).update(envelope.payload).digest('hex'));const data=JSON.parse(envelope.payload);seen.push(data);return Response.json({ok:true,reference:data.kind==='inquiry'?'INQ-20261005-ABCD1234':'APP-20261005-ABCD1234'});};
 assert.equal((await handle(formRequest('inquiry'),env,fetcher)).status,201);assert.equal((await handle(formRequest('application',{},pdf),env,fetcher)).status,201);assert.deepEqual(seen.map(x=>x.kind),['inquiry','application']);assert.equal(seen[1].files.length,1);
 const failure=await handle(formRequest('inquiry'),env,async url=>String(url).includes('siteverify')?Response.json({success:true,hostname:'tristone.example',action:'inquiry'}):Response.json({ok:false}));assert.equal(failure.status,502);assert.equal((await failure.json()).reference,undefined);
});
test('real Apps Script logic stores separate records/files and deduplicates retries',()=>{
 const sheets=new Map(),folders=new Map(),props=new Map([['INQUIRY_SHEET','inq'],['CANDIDATE_SHEET','app'],['INQUIRY_FOLDER','inq-files'],['CV_FOLDER','cv-files']]);
 function sheet(){const rows=[Array(14).fill('Header')];return {rows,getLastRow:()=>rows.length,appendRow:r=>rows.push(r),getRange:(start,col,count=1,width=1)=>({getValues:()=>rows.slice(start-1,start-1+count).map(r=>r.slice(col-1,col-1+width)),getValue:()=>rows[start-1][col-1]})};}
 for(const key of ['inq','app'])sheets.set(key,sheet());
 for(const key of ['inq-files','cv-files'])folders.set(key,{children:[],createFolder(name){const child={name,files:[],createFile(blob){this.files.push(blob);return {getUrl:()=>`https://drive.test/${key}/${name}/file`};},getUrl:()=>`https://drive.test/${key}/${name}`,setTrashed(value){this.trashed=value;}};this.children.push(child);return child;}});
 let uuid=0;const context=vm.createContext({console,Date,JSON,Number,String,Array,Error,LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},DriveApp:{getFolderById:id=>folders.get(id)},SpreadsheetApp:{openById:id=>({getSheets:()=>[sheets.get(id)]}),flush(){}},Utilities:{Charset:{UTF_8:'UTF-8'},DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,str)=>[...createHash('sha256').update(str).digest()],base64Decode:s=>[...Buffer.from(s,'base64')],newBlob:(bytes,mime,name)=>({bytes,mime,name}),getUuid:()=>('0000000'+(++uuid)).slice(-8)+'-abcd-efgh-ijkl-mnopqrstuvwx',formatDate:()=> '20261005'}});
 vm.runInContext(fs.readFileSync('google-drive-setup/WebsiteBackend.gs','utf8'),context);const property={getProperty:k=>props.get(k)};
 const inquiry={kind:'inquiry',requestId:id,fields,files:[{name:'photo.pdf',mime:'application/pdf',data:Buffer.from('%PDF-fixture').toString('base64')}]};const first=context.saveWebsiteSubmission(inquiry,property);const retry=context.saveWebsiteSubmission(inquiry,property);assert.equal(first.reference,retry.reference);assert.equal(sheets.get('inq').rows.length,2);assert.equal(folders.get('inq-files').children.length,1);assert.ok(sheets.get('inq').rows[1][3].startsWith("'="));
 const app=context.saveWebsiteSubmission({kind:'application',requestId:id,fields:candidate,files:inquiry.files},property);assert.ok(app.reference.startsWith('APP-'));assert.equal(sheets.get('app').rows.length,2);assert.equal(folders.get('cv-files').children.length,1);assert.ok(sheets.get('app').rows[1][10].includes('cv-files'));
 assert.throws(()=>context.saveWebsiteSubmission({...inquiry,fields:{...fields,name:'Changed'}},property));assert.equal(sheets.get('inq').rows.length,2);
});
