const {chromium}=require('C:/Users/sajin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const width of [390,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['','about.html','services.html','projects.html','inquiry.html','careers.html','contact.html']){await page.goto('http://127.0.0.1:8765/'+route);await page.waitForLoadState('networkidle');assert.equal(await page.locator('h1').count(),1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow at ${width} ${route}`);assert.ok(await page.title());}if(width===390){await page.goto('http://127.0.0.1:8765/');await page.getByRole('button',{name:'Menu'}).click();await page.getByRole('navigation').getByRole('link',{name:'Services',exact:true}).click();assert.ok(page.url().endsWith('/services.html'));}}
 await page.goto('http://127.0.0.1:8765/inquiry.html');assert.equal(await page.getByRole('button',{name:'Send service request'}).isDisabled(),true);assert.match(await page.locator('[data-connection]').textContent(),/will not save/);
 let submissions=0;
 await page.route('**/api/config',route=>route.fulfill({json:{ready:true,siteKey:'mock-public-key'}}));
 await page.route('https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit',route=>route.fulfill({contentType:'text/javascript',body:'window.turnstile={render:(el,o)=>{window.testSecurity=o;setTimeout(()=>o.callback("mock-token"),10);return 1},reset:()=>setTimeout(()=>window.testSecurity.callback("mock-token"),10)};'}));
 await page.route('**/api/inquiries',async route=>{submissions++;assert.ok(route.request().postDataBuffer().includes(Buffer.from('Site maintenance request')));await new Promise(r=>setTimeout(r,100));await route.fulfill({status:201,json:{ok:true,reference:'INQ-20261005-MOCK0001'}});});
 await page.goto('http://127.0.0.1:8765/inquiry.html');await page.locator('[name=name]').fill('Browser Test');await page.locator('[name=phone]').fill('+971501234567');await page.locator('[name=email]').fill('test@example.com');await page.locator('[name=location]').fill('Dubai');await page.locator('[name=service]').selectOption('Building maintenance');await page.locator('textarea[name=description]').fill('Site maintenance request');await page.locator('[name=contactMethod]').selectOption('Email');await page.locator('[name=consent]').check();await page.locator('button[type=submit]').click();await page.locator('[data-success]').waitFor({state:'visible'});assert.equal(submissions,1);assert.match(await page.locator('[data-reference]').textContent(),/^INQ-/);
 await page.route('**/api/applications',async route=>{const body=route.request().postDataBuffer();assert.ok(body.includes(Buffer.from('filename="fixture.pdf"')));await route.fulfill({status:201,json:{ok:true,reference:'APP-20261005-MOCK0001'}});});
 await page.goto('http://127.0.0.1:8765/careers.html');for(const[k,v]of Object.entries({name:'Candidate Test',phone:'+971501234567',email:'candidate@example.com',location:'Ajman',position:'Technician',experience:'3 years',qualifications:'Diploma',availability:'One month'}))await page.locator(`[name=${k}]`).fill(v);await page.locator('[name=consent]').check();assert.equal(await page.locator('[name=files]').evaluate(el=>el.checkValidity()),false);await page.locator('[name=files]').setInputFiles({name:'fixture.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.7 fixture')});await page.locator('button[type=submit]').click();await page.locator('[data-success]').waitFor({state:'visible'});assert.match(await page.locator('[data-reference]').textContent(),/^APP-/);
 await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8765/');fs.mkdirSync('qa',{recursive:true});await page.screenshot({path:'qa/home-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'qa/home-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('Responsive page checks, navigation, honest disconnected state, and both mocked form journeys passed.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});



