
import {whatsapp,socials,announcements,testimonials,certifications,projectCards,jobCards,fieldHtml} from './sections.mjs';
import {published} from './content-schema.mjs';
export const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const e=escape,lines=s=>e(s).replace(/\n/g,'<br>'),paragraphs=s=>String(s).split(/\n\n/).map(t=>`<p>${lines(t)}</p>`).join('');
export const routes=['index.html','services.html','about.html','careers.html','contact.html','inquiry.html','privacy.html','terms.html','projects.html'];
const actions=(c,cls='')=>`<div class="dual-actions ${cls}"><a class="button primary" href="/inquiry.html">${e(c.settings.customerButton)} <span aria-hidden="true">↗</span></a><a class="button secondary" href="/careers.html#apply">${e(c.settings.candidateButton)} <span aria-hidden="true">↗</span></a></div>`;
const picture=(src,alt,cls='',priority=false)=>src?`<img class="${cls}" src="${e(src)}" alt="${e(alt)}" width="1200" height="800" ${priority?'fetchpriority="high"':'loading="lazy"'} decoding="async">`:'';
const intro=(p,link='')=>`<section class="page-hero wrap ${p.image?'has-image':''}"><div><p class="eyebrow">${e(p.eyebrow)}</p><h1>${lines(p.headline)}</h1><p class="lead">${e(p.intro)}</p>${link}</div>${p.image?`<figure>${picture(p.image,p.imageAlt,'',true)}<figcaption>Illustrative service photography</figcaption></figure>`:''}</section>`;
const serviceBriefs=c=>`<div class="service-briefs">${c.services.map((s,i)=>`<article><span class="card-number">${String(i+1).padStart(2,'0')}</span><h3>${e(s.title)}</h3><p>${e(s.summary||s.description.split(".")[0]+".")}</p><a class="text-link" href="/inquiry.html?service=${encodeURIComponent(s.value)}">${e(c.settings.customerButton)} ↗</a></article>`).join('')}</div>`;
const serviceRows=c=>`<div class="service-editorial">${c.services.map((s,i)=>`<article class="service-row ${s.image?'':'no-image'}" id="${e(s.id)}">${s.image?`<figure>${picture(s.image,s.imageAlt)}</figure>`:''}<div><p class="eyebrow">SERVICE ${String(i+1).padStart(2,'0')}</p><h2>${e(s.title)}</h2><p>${e(s.description)}</p><a class="button primary" href="/inquiry.html?service=${encodeURIComponent(s.value)}">${e(c.settings.customerButton)} ↗</a></div></article>`).join('')}</div>`;
const form=(c,kind)=>{const career=kind==='application',f=c.forms[kind];const field=(name,type='text',options=null)=>fieldHtml(f.fields[name],name,type,options);return `<section class="wrap section form-layout" id="${career?'apply':'request'}"><div><p class="form-notice" role="status" data-connection>Checking online submissions…</p><form data-kind="${kind}"><h2>${e(f.heading)}</h2><p>${e(f.intro)}</p><p class="form-help">Fields marked * are required.</p><div class="form-grid">${field('name')}${career?'':field('company')}${field('phone','tel')}${field('email','email')}${field('location')}${career?field('position')+field('experience')+field('qualifications','textarea')+field('availability'):field('service','text',c.services.map(x=>x.value).concat('Other / discuss requirements'))+field('contactMethod','text',['Email','Phone'])}</div>${career?'':field('description','textarea')}<div class="extra-fields">${f.extras.map(x=>fieldHtml(x,'extra_'+x.id,x.type)).join('')}</div><label class="upload-label">${career?'Upload your CV *':'Photos or documents (optional)'}<input name="files" type="file" ${career?'required':'multiple'} accept="${career?'.pdf,.doc,.docx':'.pdf,.doc,.docx,.jpg,.jpeg,.png'}"><span class="field-help">${career?'One PDF, DOC or DOCX, up to 5 MB.':'Up to 3 files, 5 MB each and 10 MB total. PDF, DOC, DOCX, JPG or PNG.'}</span></label><div class="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="consent"><input type="checkbox" name="consent" value="yes" required><span>${e(f.consent)} <a href="/privacy.html">Privacy policy</a></span></label><div data-security></div><p data-error role="alert" class="form-error" hidden></p><button class="button primary" type="submit" disabled>${e(f.submit)} ↗</button></form><div class="confirmation" data-success role="status" hidden><p class="eyebrow">${career?'APPLICATION RECEIVED':'SERVICE REQUEST RECEIVED'}</p><h2>Thank you.</h2><p>${e(f.confirmation)}</p><strong data-reference></strong><a class="text-link" href="/">Return to Home ↗</a></div></div><aside class="form-aside"><p class="eyebrow">${career?'CANDIDATE APPLICATIONS':'CUSTOMER ENQUIRIES'}</p><h3>${career?'Your experience matters.':'A clear scope starts here.'}</h3><p>${career?'Your application and CV are reviewed separately from customer service requests.':'Share the site location, scope and preferred dates. For manpower, add the roles, headcount and duration.'}</p><hr><a href="mailto:${e(c.email)}">${e(c.email)}</a>${whatsapp(c,kind)}<p class="field-help">A submission does not confirm a booking or an offer of employment.</p></aside></section>`;};
export function renderPage(c,file,origin){const key={'index.html':'home','services.html':'servicesPage','about.html':'about','careers.html':'careers','contact.html':'contact'}[file];let p=key?c[key]:{};let body='';const copy=c.copy;
 if(file==='index.html')body=`<section class="home-hero"><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow">${e(p.eyebrow)}</p><h1>${lines(p.headline)}</h1><p class="lead">${e(p.intro)}</p>${actions(c)}<div class="hero-proof"><span>Ajman-registered</span><span>${e(c.coverage)}</span></div></div>${p.image?`<figure class="hero-photo">${picture(p.image,p.imageAlt,'',true)}<figcaption>Building care & workforce support<span>Illustrative service photography</span></figcaption></figure>`:''}</div></section><section class="wrap section"><div class="section-heading"><div><p class="eyebrow">${e(copy.servicesTag)}</p><h2>${lines(p.sectionTitle)}</h2></div><p>${e(p.sectionText)}</p></div>${serviceBriefs(c)}</section>${c.trust.length?`<section class="principles"><div class="wrap"><p class="eyebrow">OUR APPROACH</p><h2>${lines(copy.approachHeading)}</h2><div class="trust-grid">${c.trust.map((t,i)=>`<article><span>0${i+1}</span><h3>${e(t.title)}</h3><p>${e(t.text)}</p></article>`).join('')}</div></div></section>`:''}<section class="wrap section company-intro"><div><p class="eyebrow">ABOUT TRISTONE</p><h2>${lines(c.about.sectionTitle)}</h2></div><div><p>${e(c.about.intro)}</p><a class="text-link" href="/about.html">${e(copy.aboutLink)} ↗</a></div></section>${published(c.projects).length?`<section class="wrap section"><p class="eyebrow">PROJECTS</p><h2>${e(c.projectsHeading)}</h2>${projectCards(c)}</section>`:''}${testimonials(c)}`;
 else if(file==='services.html')body=intro(p)+`<section class="wrap section services-main">${serviceRows(c)}</section><section class="process wrap section"><p class="eyebrow">HOW IT WORKS</p><h2>${lines(copy.processHeading)}</h2><p>${e(copy.processIntro)}</p><ol class="process-steps">${[['stepOneHeading','stepOneText'],['stepTwoHeading','stepTwoText'],['stepThreeHeading','stepThreeText']].map(([h,t])=>`<li><h3>${e(copy[h])}</h3><p>${e(copy[t])}</p></li>`).join('')}</ol></section>`;
 else if(file==='about.html')body=intro(p)+`<section class="wrap section about-content"><div><p class="eyebrow">OUR COMPANY</p><h2>${lines(p.sectionTitle)}</h2>${paragraphs(p.sectionText)}</div><aside class="company-details"><h3>${e(copy.companyHeading)}</h3><dl><dt>Legal name</dt><dd>${e(c.legalName)}</dd><dt>Trade licence</dt><dd>${e(c.licence)}</dd><dt>Licensed activities</dt><dd>${lines(copy.licensedActivities)}</dd><dt>Registered office</dt><dd>${e(c.office)}</dd></dl></aside></section>${certifications(c)}`;
 else if(file==='careers.html')body=intro(p,`<a class="button primary" href="#apply">${e(c.settings.candidateButton)} ↗</a>`)+`<section class="wrap vacancies"><p class="eyebrow">${e(c.settings.jobsHeading)}</p>${jobCards(c)}</section>`+form(c,'application');
 else if(file==='contact.html')body=intro(p)+`<section class="wrap section contact-layout"><div><p class="eyebrow">${e(copy.contactHeading)}</p><a class="contact-email" href="mailto:${e(c.email)}">${e(c.email)} ↗</a><p>${e(copy.contactIntro)}</p>${c.phone?`<p>Phone: <a href="tel:${e(c.phone.replace(/[^+\d]/g,''))}">${e(c.phone)}</a></p>`:''}${whatsapp(c,'inquiry')}${whatsapp(c,'application')}<div class="contact-routes">${actions(c)}</div></div><dl><dt>Registered office</dt><dd>${e(c.office)}</dd><dt>Office hours</dt><dd>${e(c.hours)}</dd><dt>Service coverage</dt><dd>${e(c.coverage)}</dd></dl></section>`;
 else if(file==='inquiry.html'){p={title:c.forms.inquiry.heading,description:c.forms.inquiry.intro,eyebrow:'CUSTOMER ENQUIRIES',headline:copy.inquiryHeading,intro:copy.inquiryIntro};body=intro(p)+form(c,'inquiry');}
 else if(file==='privacy.html'||file==='terms.html'){const privacy=file==='privacy.html';p={title:c.policySeo[privacy?'privacyTitle':'termsTitle'],description:c.policySeo[privacy?'privacyDescription':'termsDescription']};body=`<section class="wrap section policy"><p class="eyebrow">INFORMATION & POLICIES</p><h1>${e(p.title)}</h1>${paragraphs(privacy?c.privacy:c.terms)}</section>`;}
 else if(file==='projects.html'){p={title:c.policySeo.projectsTitle,description:c.policySeo.projectsDescription};body=`<section class="wrap section"><p class="eyebrow">PROJECTS</p><h1>${e(c.projectsHeading)}</h1><p class="lead">${e(c.projectsIntro)}</p>${projectCards(c)||'<p>Project details will be published as work is completed.</p>'}</section>`;}else return null;
 const nav=[['index.html','Home'],['about.html','About Us'],['services.html','Services'],['careers.html','Careers'],['contact.html','Contact']];const title=p.title+' | '+c.brand,canonical=origin+'/'+(file==='index.html'?'':file);const og=c.home.image.startsWith('https:')?c.home.image:origin+c.home.image;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(p.description)}"><link rel="canonical" href="${e(canonical)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(p.description)}"><meta property="og:type" content="website"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(og)}"><meta name="theme-color" content="#082750"><link rel="stylesheet" href="/styles.css"><link rel="icon" href="/logo.png"><script type="module" src="/site.js"></script></head><body><a class="skip" href="#main">Skip to content</a><div class="topline"><div class="wrap"><span>${e(c.coverage)} · Building maintenance & manpower</span><a href="mailto:${e(c.email)}">${e(c.email)}</a></div></div><header><div class="wrap header"><a class="brand" href="/" aria-label="${e(c.brand)} Home"><img src="/logo.png" width="66" height="44" alt=""><span>${e(c.brand)}<small>BUILDING MAINTENANCE</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation">${nav.map(([f,label])=>`<a href="/${f}" ${file===f?'aria-current="page"':''}>${label}</a>`).join('')}</nav>${actions(c,'header-actions')}</div></header><main id="main">${announcements(c)}${body}</main><footer><div class="wrap footer-grid"><div class="footer-brand"><strong>${e(c.brand)}</strong><p>${e(c.settings.footerText)}</p><div class="social-links">${socials(c)}</div></div><div><h3>${e(copy.footerContactHeading)}</h3><a href="mailto:${e(c.email)}">${e(c.email)}</a><p>${e(c.office)}</p>${c.phone?`<p><a href="tel:${e(c.phone.replace(/[^+\d]/g,''))}">${e(c.phone)}</a></p>`:''}</div><div><h3>${e(copy.footerLinksHeading)}</h3><a href="/inquiry.html">${e(c.settings.customerButton)}</a><a href="/careers.html#apply">${e(c.settings.candidateButton)}</a>${published(c.projects).length?'<a href="/projects.html">Projects</a>':''}<a href="/privacy.html">${e(c.policySeo.privacyTitle)}</a><a href="/terms.html">${e(c.policySeo.termsTitle)}</a></div></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} ${e(c.settings.footerCopyright)}</span><span>Licence ${e(c.licence.split(' · ')[0])}</span></div></footer>${actions(c,'mobile-actions')}</body></html>`;
}
