import {PDFDocument,PDFDict,PDFArray,PDFName} from 'pdf-lib';
import jpeg from 'jpeg-js';
import UPNG from 'upng-js';
import {SecurityError,digest} from './security.mjs';
const MAX=5*1024*1024;
const forbidden=new Set(['JavaScript','JS','OpenAction','AA','Launch','URI','SubmitForm','ImportData','GoToR','GoToE','EmbeddedFiles','EF','RichMedia','XFA','AcroForm','Encrypt','ObjStm','XRef','Collection','Sound','Movie','3D','Rendition']);
export async function passivePdf(bytes){if(!bytes.length||bytes.length>MAX)throw new SecurityError('PDF must be no larger than 5 MB.',413);const text=new TextDecoder('latin1').decode(bytes);if(!/^%PDF-1\.[0-7]\r?\n/.test(text)||!/\bstartxref\s+\d+\s+%%EOF\s*$/.test(text)||!/[\r\n]xref[\r\n]/.test(text))throw new SecurityError('Upload a complete, standard PDF document.',400);const names=text.replace(/#([0-9a-f]{2})/gi,(_,n)=>String.fromCharCode(parseInt(n,16)));if(/\/(?:JavaScript|JS|OpenAction|AA|Launch|URI|SubmitForm|ImportData|GoToR|GoToE|EmbeddedFiles|EF|RichMedia|XFA|AcroForm|Encrypt|ObjStm|XRef|Collection|Sound|Movie|3D|Rendition)\b/.test(names))throw new SecurityError('Interactive, encrypted or embedded-content PDFs are not accepted.',400);
try{const doc=await PDFDocument.load(bytes,{ignoreEncryption:false,throwOnInvalidObject:true,updateMetadata:false});if(doc.isEncrypted||doc.getPageCount()<1||doc.getPageCount()>50||doc.context.enumerateIndirectObjects().length>5000)throw new Error();const seen=new Set();function inspect(obj,depth=0){if(depth>50)throw new Error();if(!obj||seen.has(obj))return;seen.add(obj);if(obj instanceof PDFDict){for(const[k,v]of obj.entries()){if(forbidden.has(k.decodeText()))throw new Error();inspect(v,depth+1);}}else if(obj instanceof PDFArray){for(let i=0;i<obj.size();i++)inspect(obj.get(i),depth+1);}else if(obj instanceof PDFName&&forbidden.has(obj.decodeText()))throw new Error();if(obj.dict)inspect(obj.dict,depth+1);}let inflated=0;for(const[,obj]of doc.context.enumerateIndirectObjects()){inspect(obj);if(obj.contents&&obj.dict){const f=obj.dict.lookup(PDFName.of('Filter'));if(f){if(!(f instanceof PDFName))throw new Error();const name=f.decodeText();if(name==='FlateDecode'){inflated+=await inflateBounded(obj.contents,32*1024*1024-inflated);if(inflated>32*1024*1024)throw new Error();}else if(name==='DCTDecode')jpeg.decode(obj.contents,{useTArray:true,tolerantDecoding:false,maxResolutionInMP:4,maxMemoryUsageInMB:64});else throw new Error();}}}for(const page of doc.getPages()){const {width,height}=page.getSize();if(!Number.isFinite(width)||!Number.isFinite(height)||width<=0||height<=0||width>14400||height>14400)throw new Error();}const clean=await PDFDocument.create();clean.setCreationDate(new Date(0));clean.setModificationDate(new Date(0));clean.setProducer('TriStone intake');clean.setCreator('TriStone intake');const pages=await clean.copyPages(doc,doc.getPageIndices());pages.forEach(p=>clean.addPage(p));const result=await clean.save({useObjectStreams:false,addDefaultPage:false,updateFieldAppearances:false});if(result.length>MAX)throw new Error();return result;}catch(error){throw new SecurityError('This PDF is malformed or contains unsupported content. Export a simple PDF and retry.',400);}}
function crc32(bytes){let n=0xffffffff;for(const b of bytes){n^=b;for(let k=0;k<8;k++)n=(n>>>1)^((n&1)?0xedb88320:0);}return (n^0xffffffff)>>>0;}
async function inflateBounded(bytes,limit){const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate')),reader=stream.getReader();let size=0;for(;;){const r=await reader.read();if(r.done)return size;if((size+=r.value.length)>limit){await reader.cancel();throw new Error('Compressed content too large');}}}
export async function cleanImage(bytes,type){
 if(!bytes.length||bytes.length>MAX)throw new SecurityError('Image must be no larger than 5 MB.',413);
 try{let result;
 if(type==='image/jpeg'){const image=jpeg.decode(bytes,{useTArray:true,tolerantDecoding:false,maxResolutionInMP:4,maxMemoryUsageInMB:64});result=new Uint8Array(jpeg.encode(image,85).data);}
 else if(type==='image/png'){
  if(bytes.length<33||![137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n))throw new Error();
  const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),w=view.getUint32(16),h=view.getUint32(20);if(!w||!h||w>4096||h>4096||w*h>4000000)throw new Error();
  let offset=8,ended=false;const chunks=[bytes.slice(0,8)],compressed=[];while(offset+12<=bytes.length){const size=view.getUint32(offset);if(size>bytes.length-offset-12)throw new Error();const name=String.fromCharCode(...bytes.slice(offset+4,offset+8));if(crc32(bytes.slice(offset+4,offset+8+size))!==view.getUint32(offset+8+size))throw new Error();if(offset===8&&name!=='IHDR'||name==='IHDR'&&offset!==8||['acTL','fcTL','fdAT'].includes(name))throw new Error();if(!['IHDR','PLTE','tRNS','IDAT','IEND'].includes(name)&&name[0]===name[0].toUpperCase())throw new Error();if(['IHDR','PLTE','tRNS','IDAT','IEND'].includes(name))chunks.push(bytes.slice(offset,offset+size+12));if(name==='IDAT')compressed.push(bytes.slice(offset+8,offset+8+size));offset+=size+12;if(name==='IEND'){if(size)throw new Error();ended=true;break;}}
  if(!ended||offset!==bytes.length||!compressed.length)throw new Error();await inflateBounded(new Uint8Array(await new Blob(compressed).arrayBuffer()),w*h*8+h*16+1024);
  const safe=await new Blob(chunks).arrayBuffer(),png=UPNG.decode(safe);if(png.width!==w||png.height!==h)throw new Error();const frames=UPNG.toRGBA8(png);if(frames.length!==1||frames[0].byteLength!==w*h*4)throw new Error();result=new Uint8Array(UPNG.encode(frames,w,h,0,[],true));
 }else throw new Error();if(result.length>MAX)throw new Error();return result;
 }catch{throw new SecurityError('Use a complete JPG or PNG image up to 4 megapixels.',400);}
}
export async function submissionFiles(files,kind){if(!Array.isArray(files)||files.length>(kind==='application'?1:3)||(kind==='application'&&files.length!==1))throw new SecurityError('Upload one PDF CV, or up to three PDF inquiry documents.',400);let total=0;const out=[];for(const file of files){if(!/\.pdf$/i.test(file.name)||!['','application/pdf'].includes(file.type))throw new SecurityError('Submission documents must be PDF only.',400);total+=file.size;if(total>10*1024*1024)throw new SecurityError('Documents must total no more than 10 MB.',413);const bytes=await passivePdf(new Uint8Array(await file.arrayBuffer()));let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));out.push({name:file.name.replace(/[^\w. -]/g,'_').slice(0,120),mime:'application/pdf',data:btoa(raw),sha256:await digest(bytes),policy:'passive-pdf-v1',size:bytes.length});}if(out.reduce((n,f)=>n+f.size,0)>10*1024*1024)throw new SecurityError('Documents must total no more than 10 MB.',413);return out;}
