/* TriStone submission-only backend v2. Uses Advanced Drive/Sheets services
 * and the narrow drive.file scope. No DriveApp, browse, photo, trash or delete API.
 * Configure a 64-character random hexadecimal BRIDGE_SECRET privately first.
 */
const PURPOSE = 'tristone-intake-v2';
const INQUIRY_HEADERS = ['Received','Reference','Name','Company','Phone','Email','Location','Service','Description','Preferred contact','Files folder','File links','Request ID','Digest'];
const CANDIDATE_HEADERS = ['Received','Reference','Name','Phone','Email','Current location','Position','Experience','Qualifications','Availability','CV folder','CV links','Request ID','Digest'];
function hex(bytes){return bytes.map(b=>('0'+((b+256)%256).toString(16)).slice(-2)).join('');}
function equalSignature(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
function jsonResult(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON);}
function safeCell(value){const s=String(value||'');return /^[=+\-@\t\r\n]/.test(s)?"'"+s:s;}
function setupWebsiteBackend(){
 const lock=LockService.getScriptLock();lock.waitLock(30000);
 try{const p=PropertiesService.getScriptProperties();if(!/^[a-f0-9]{64}$/.test(p.getProperty('BRIDGE_SECRET')||''))throw new Error('Set a random 64-character BRIDGE_SECRET in private Script Properties first.');
 if(!p.getProperty('ROOT_FOLDER')){const f=Drive.Files.create({name:'TriStone Website Submissions',mimeType:'application/vnd.google-apps.folder',appProperties:{purpose:PURPOSE}},null,{fields:'id'});p.setProperty('ROOT_FOLDER',f.id);}
 const root=p.getProperty('ROOT_FOLDER');
 function folder(key,name){if(!p.getProperty(key)){const f=Drive.Files.create({name:name,mimeType:'application/vnd.google-apps.folder',parents:[root],appProperties:{purpose:PURPOSE}},null,{fields:'id'});p.setProperty(key,f.id);}}
 function sheet(key,name,headers){if(p.getProperty(key))return;const s=Sheets.Spreadsheets.create({properties:{title:name,timeZone:'Asia/Dubai'},sheets:[{properties:{title:'Records',gridProperties:{frozenRowCount:1}}}]},{fields:'spreadsheetId'});const info=Drive.Files.get(s.spreadsheetId,{fields:'parents'});Drive.Files.update({appProperties:{purpose:PURPOSE}},s.spreadsheetId,null,{addParents:root,removeParents:(info.parents||[]).join(','),fields:'id'});Sheets.Spreadsheets.Values.update({values:[headers]},s.spreadsheetId,'Records!A1:N1',{valueInputOption:'RAW'});p.setProperty(key,s.spreadsheetId);}
 folder('INQUIRY_FOLDER','Customer Inquiry Files');folder('CV_FOLDER','Candidate CVs');sheet('INQUIRY_SHEET','Customer Inquiries',INQUIRY_HEADERS);sheet('CANDIDATE_SHEET','Candidate Applications',CANDIDATE_HEADERS);
 console.log('Setup complete. Keep the app-created submission folder private. No secrets are logged.');
 }finally{lock.releaseLock();}
}
function doGet(){return jsonResult({ok:false,error:'Only authenticated website submissions are accepted.'});}
function validatePdfFile(file){
 if(!file||file.mime!=='application/pdf'||file.policy!=='passive-pdf-v1'||typeof file.name!=='string'||file.name.length>120||!/\.pdf$/i.test(file.name)||typeof file.data!=='string'||file.data.length>7*1024*1024||!/^[a-f0-9]{64}$/.test(file.sha256||'')||!Number.isSafeInteger(file.size))throw new Error('Invalid PDF');
 if(!/^[A-Za-z0-9+/]*={0,2}$/.test(file.data)||file.data.length%4!==0)throw new Error('Invalid encoding');
 const bytes=Utilities.base64Decode(file.data);if(!bytes.length||bytes.length>5*1024*1024||bytes.length!==file.size||hex(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,bytes))!==file.sha256)throw new Error('Invalid PDF');
 const text=bytes.map(b=>String.fromCharCode((b+256)%256)).join('');const names=text.replace(/#([0-9a-f]{2})/gi,(_,v)=>String.fromCharCode(parseInt(v,16)));
 if(!/^%PDF-1\.[0-7]\r?\n/.test(text)||!/\bstartxref\s+\d+\s+%%EOF\s*$/.test(text)||!/[\r\n]xref[\r\n]/.test(text)||!/\/Type\s*\/Catalog\b/.test(names)||!/\/Type\s*\/Page\b/.test(names)||!/\btrailer\s*<</.test(text)||/\/(JavaScript|JS|OpenAction|AA|Launch|URI|SubmitForm|ImportData|GoToR|GoToE|EmbeddedFiles|EF|RichMedia|XFA|AcroForm|Encrypt|ObjStm|XRef|Collection|Sound|Movie|3D|Rendition)\b/.test(names))throw new Error('Unsupported PDF');
 return Utilities.newBlob(bytes,'application/pdf',file.name.replace(/[^\w. -]/g,'_'));
}
function assertDestination(id,root,folder){if(!id)throw new Error('Not configured');const f=Drive.Files.get(id,{fields:'id,parents,mimeType,appProperties,trashed'});if(f.trashed||f.appProperties?.purpose!==PURPOSE||(root&&!(f.parents||[]).includes(root))||(folder&&f.mimeType!=='application/vnd.google-apps.folder'))throw new Error('Destination not approved');const permissions=Drive.Permissions.list(id,{fields:'permissions(type)'}).permissions||[];if(permissions.some(x=>['anyone','domain'].includes(x.type)))throw new Error('Submission storage must be private');}
function checkFields(data){const q=data.fields;if(!q||typeof q!=='object'||Array.isArray(q))throw new Error('Invalid fields');const keys=data.kind==='inquiry'?['name','company','phone','email','location','service','description','contactMethod']:['name','phone','email','location','position','experience','qualifications','availability'];if(Object.keys(q).some(k=>!keys.includes(k)))throw new Error('Unexpected fields');keys.forEach(k=>{if(typeof q[k]!=='string'||q[k].length>(['description','qualifications'].includes(k)?4000:200)||(k!=='company'&&!q[k].trim()))throw new Error('Invalid fields');});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(q.email)||!/^\+?[\d ()-]{7,25}$/.test(q.phone)||(data.kind==='inquiry'&&!['Email','Phone','[Not provided]'].includes(q.contactMethod)))throw new Error('Invalid fields');return q;}
function doPost(e){try{
 if(!e?.postData||typeof e.postData.contents!=='string'||e.postData.contents.length>16*1024*1024)throw new Error('Invalid request');
 const envelope=JSON.parse(e.postData.contents),p=PropertiesService.getScriptProperties(),secret=p.getProperty('BRIDGE_SECRET');if(!/^[a-f0-9]{64}$/.test(secret||'')||typeof envelope.payload!=='string')throw new Error('Not configured');
 const expected=hex(Utilities.computeHmacSha256Signature(envelope.payload,secret,Utilities.Charset.UTF_8));if(!equalSignature(envelope.signature,expected))throw new Error('Unauthorised');
 const data=JSON.parse(envelope.payload);if(data.version!==2||data.audience!=='tristone-submissions-v2'||data.operation!=='submit'||!['inquiry','application'].includes(data.kind)||!Number.isSafeInteger(data.timestamp)||Math.abs(Date.now()-data.timestamp)>120000||!/^[a-f0-9-]{36}$/.test(data.nonce||'')||!/^[a-f0-9-]{36}$/.test(data.requestId||'')||Object.keys(data).some(k=>!['version','audience','operation','kind','timestamp','nonce','requestId','fields','files'].includes(k)))throw new Error('Invalid request');
 const fields=checkFields(data),files=data.files;if(!Array.isArray(files)||files.length>(data.kind==='application'?1:3)||(data.kind==='application'&&files.length!==1))throw new Error('Invalid files');const decoded=files.map(validatePdfFile),bytes=files.reduce((n,f)=>n+f.size,0);if(bytes>10*1024*1024)throw new Error('Too large');
 return jsonResult(saveSubmission(data,fields,files,decoded,bytes,p));
 }catch{return jsonResult({ok:false,error:'The submission was not saved or confirmed. Please retry later.'});}}
function saveSubmission(data,fields,files,decoded,bytes,p){const lock=LockService.getScriptLock();lock.waitLock(25000);try{
 const now=Date.now(),properties=p.getProperties();Object.keys(properties).filter(k=>k.startsWith('nonce:')&&Number(properties[k])<now).forEach(k=>p.deleteProperty(k));if(p.getProperty('nonce:'+data.nonce))throw new Error('Replay rejected');if(Object.keys(p.getProperties()).filter(k=>k.startsWith('nonce:')).length>=500)throw new Error('Request limit');p.setProperty('nonce:'+data.nonce,String(now+180000));
 const inquiry=data.kind==='inquiry',sheet=p.getProperty(inquiry?'INQUIRY_SHEET':'CANDIDATE_SHEET'),parent=p.getProperty(inquiry?'INQUIRY_FOLDER':'CV_FOLDER'),root=p.getProperty('ROOT_FOLDER');assertDestination(root,null,true);assertDestination(sheet,root,false);assertDestination(parent,root,true);
 const digest=hex(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,JSON.stringify({kind:data.kind,fields:fields,files:files}),Utilities.Charset.UTF_8));const rows=Sheets.Spreadsheets.Values.get(sheet,'Records!A2:N').values||[];for(const row of rows)if(row[12]===data.requestId){if(row[13]!==digest)throw new Error('Changed request');return {ok:true,reference:row[1]};}
 const pendingKey='pending:'+data.requestId;if(p.getProperty(pendingKey))throw new Error('Previous submission requires owner reconciliation');
 const day=Utilities.formatDate(new Date(),'Asia/Dubai','yyyy-MM-dd');const quota=JSON.parse(p.getProperty('QUOTA')||'{}');if(quota.day!==day){quota.day=day;quota.count=0;quota.bytes=0;}quota.total=quota.total||0;quota.records=quota.records||0;if(quota.count>=200||quota.bytes+bytes>50*1024*1024||quota.total+bytes>500*1024*1024||quota.records>=2000)throw new Error('Storage or submission limit');quota.count++;quota.bytes+=bytes;quota.total+=bytes;quota.records++;p.setProperty('QUOTA',JSON.stringify(quota));p.setProperty(pendingKey,digest);
 const reference=(inquiry?'INQ-':'APP-')+Utilities.formatDate(new Date(),'Asia/Dubai','yyyyMMdd')+'-'+Utilities.getUuid().slice(0,12).toUpperCase();let folder='';const urls=[];if(decoded.length){const f=Drive.Files.create({name:reference,mimeType:'application/vnd.google-apps.folder',parents:[parent],appProperties:{purpose:PURPOSE}},null,{fields:'id'});folder=f.id;decoded.forEach(blob=>{const file=Drive.Files.create({name:blob.getName(),parents:[folder],appProperties:{purpose:PURPOSE}},blob,{fields:'id'});urls.push('https://drive.google.com/file/d/'+file.id+'/view');});}
 const folderLink=folder?'https://drive.google.com/drive/folders/'+folder:'';const row=inquiry?[new Date().toISOString(),reference,fields.name,fields.company,fields.phone,fields.email,fields.location,fields.service,fields.description,fields.contactMethod,folderLink,urls.join('\n'),data.requestId,digest]:[new Date().toISOString(),reference,fields.name,fields.phone,fields.email,fields.location,fields.position,fields.experience,fields.qualifications,fields.availability,folderLink,urls.join('\n'),data.requestId,digest];
 Sheets.Spreadsheets.Values.append({values:[row.map(safeCell)]},sheet,'Records!A:N',{valueInputOption:'RAW',insertDataOption:'INSERT_ROWS'});p.deleteProperty(pendingKey);return {ok:true,reference:reference};
 }finally{lock.releaseLock();}}
