
const status=document.querySelector('#editor-status'),form=document.querySelector('#editor-form'),panel=document.querySelector('#editor-panel'),tabs=document.querySelector('#editor-tabs');let content,revision=0,dirty=false,busy=false,uploads=0,section='home';
const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text)el.textContent=text;if(cls)el.className=cls;return el;};const message=(text,error=false)=>{status.textContent=text;status.classList.toggle('error',error);};
const groups=[['home','Home'],['about','About Us'],['servicesPage','Services page'],['services','Service list'],['careers','Careers'],['jobs','Job vacancies'],['contact','Contact page'],['company','Contact & company'],['copy','Section wording'],['forms','Forms'],['buttons','Buttons'],['whatsapp','WhatsApp'],['social','Social links'],['banner','Banner'],['announcements','Announcements'],['testimonials','Testimonials'],['projects','Projects'],['certifications','Certifications'],['footer','Footer'],['trust','Trust points'],['privacy','Privacy policy'],['terms','Terms'],['policySeo','Policy & project SEO'],['portfolio','Portfolio wording']];
const labels={title:'Title',description:'Description',summary:'Short summary for Home',eyebrow:'Small heading',headline:'Main headline',intro:'Introduction',image:'Image URL',imageAlt:'Image description (accessibility)',sectionTitle:'Section heading',sectionText:'Section text',brand:'Company display name',email:'Contact email',phone:'Phone (blank hides it)',coverage:'Service coverage',office:'Registered office',hours:'Working hours',legalName:'Legal company name',licence:'Trade licence',value:'Service option in the request form',icon:'Service icon',projectsHeading:'Portfolio heading',projectsIntro:'Portfolio introduction',customerButton:'Customer button label',candidateButton:'Candidate button label',whatsappCountryCode:'Country code (digits only, e.g. 971)',whatsappNumber:'WhatsApp number (without country code or spaces)',whatsappCustomerMessage:'Default customer message',whatsappCandidateMessage:'Default candidate message',otherSocialLabel:'Other social platform name',otherSocialUrl:'Other social link',bannerEnabled:'Show banner',bannerImage:'Banner image',bannerImageAlt:'Banner image description',bannerText:'Banner message',footerText:'Footer description',footerCopyright:'Copyright company name',location:'Location',type:'Employment type',requirements:'Requirements',closing:'Closing date',client:'Client name',role:'Client role / company',quote:'Testimonial',issuer:'Issuer',url:'Link',status:'Publication status',enabled:'Show field',required:'Required field',label:'Field label',submit:'Submit button text',confirmation:'Confirmation message',consent:'Consent wording'};
const collectionDefaults={services:()=>({id:'service-'+crypto.randomUUID().slice(0,8),title:'New service',value:'New service '+(content.services.length+1),description:'',summary:'',image:'',imageAlt:'',icon:'tools'}),trust:()=>({title:'New point',text:''}),jobs:()=>({id:crypto.randomUUID(),title:'',location:'',type:'',requirements:'',closing:'',status:'Draft'}),projects:()=>({id:crypto.randomUUID(),title:'',location:'',description:'',image:'',imageAlt:'',status:'Draft'}),testimonials:()=>({id:crypto.randomUUID(),client:'',role:'',quote:'',status:'Draft'}),certifications:()=>({id:crypto.randomUUID(),title:'',issuer:'',description:'',url:'',image:'',imageAlt:'',status:'Draft'}),announcements:()=>({id:crypto.randomUUID(),title:'',text:'',url:'',status:'Draft'})};
function inputCard(holder,obj,key,core=false,page=false){if(key==='id')return;const label=node('label',page&&key==='title'?'SEO title':page&&key==='description'?'Meta description':labels[key]||key.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase()));let input;const value=obj[key];
 if(typeof value==='boolean'){input=document.createElement('input');input.type='checkbox';input.checked=value;input.disabled=core;label.className='editor-checkbox';input.addEventListener('change',()=>{obj[key]=input.checked;dirty=true;});}
 else {const choices=key==='status'?['Draft','Published','Closed']:key==='icon'?['building','bolt','people','tools']:key==='type'&&'required'in obj?['text','textarea','date','number']:null;if(choices){input=document.createElement('select');choices.forEach(v=>{const option=node('option',v);option.value=v;input.append(option);});}else if(['intro','description','sectionText','privacy','terms','text','quote','requirements','consent','confirmation'].includes(key)||String(value).includes('\n')){input=document.createElement('textarea');input.rows=['privacy','terms'].includes(key)?12:4;}else{input=document.createElement('input');if(key==='closing')input.type='date';}input.value=value||'';input.maxLength=['privacy','terms'].includes(key)?12000:4000;input.addEventListener('input',()=>{obj[key]=input.value;dirty=true;});}label.append(input);holder.append(label);
 if(key==='image'||key==='bannerImage'){const img=document.createElement('img');img.className='editor-image';img.alt='Current image preview';img.src=value||'';img.hidden=!value;img.addEventListener('error',()=>{img.hidden=true;});holder.append(img);input.addEventListener('change',()=>{img.src=input.value;img.hidden=!input.value;});const uploadLabel=node('label','Replace with an uploaded photo'),upload=document.createElement('input');upload.type='file';upload.accept='.jpg,.jpeg,.png';uploadLabel.append(upload);holder.append(uploadLabel,node('small','JPG or PNG, up to 5 MB. Only upload photographs you own or are allowed to publish.'));
 upload.addEventListener('change',async()=>{const file=upload.files[0];if(!file)return;if(file.size>5*1024*1024){message('Choose an image up to 5 MB.',true);return;}uploads++;upload.disabled=true;message('Uploading photo…');try{const response=await fetch('/api/admin/images',{method:'POST',headers:{'Content-Type':file.type},body:file});const data=await response.json();if(!response.ok)throw new Error(data.error||'Upload failed.');obj[key]=data.url;input.value=data.url;img.src=data.url;img.hidden=false;dirty=true;message('Photo uploaded. Save changes to place it on the website.');}catch(e){message(e.message,true);}finally{uploads--;upload.disabled=false;}});}
}
const card=(title)=>{const el=node('div','','editor-card');el.append(node('h2',title));panel.append(el);return el;};
function arrayEditor(holder,list,create,label,max=50){list.forEach((item,index)=>{const box=node('section','','editor-item');box.append(node('h3',label+' '+(index+1)));Object.keys(item).forEach(key=>inputCard(box,item,key));const remove=node('button','Remove '+label.toLowerCase(),'remove-service');remove.type='button';remove.addEventListener('click',()=>{if(list===content.services&&list.length===1){message('Keep at least one service.',true);return;}list.splice(index,1);dirty=true;render();});box.append(remove);holder.append(box);});const add=node('button','Add '+(label==='Service'?'a service':label.toLowerCase()),'button secondary');add.type='button';add.addEventListener('click',()=>{if(list.length>=max){message('The maximum number of entries has been reached.',true);return;}list.push(create());dirty=true;render();});holder.append(add);}
function render(){panel.replaceChildren();for(const button of tabs.children)button.setAttribute('aria-pressed',String(button.dataset.section===section));const box=card(groups.find(g=>g[0]===section)[1]);
 if(['home','about','servicesPage','careers','contact'].includes(section))Object.keys(content[section]).forEach(key=>inputCard(box,content[section],key,false,true));
 else if(section==='company')for(const key of ['brand','email','phone','coverage','office','hours','legalName','licence'])inputCard(box,content,key);
 else if(['privacy','terms'].includes(section))inputCard(box,content,section);
 else if(section==='portfolio')for(const key of ['projectsHeading','projectsIntro'])inputCard(box,content,key);
 else if(['copy','policySeo'].includes(section))Object.keys(content[section]).forEach(key=>inputCard(box,content[section],key));
 else if(section==='forms'){box.append(node('p','Name, email and phone stay required for reliable contact. Candidate CV uploads remain required. Other fields can be labelled, hidden or made optional.'));for(const kind of ['inquiry','application']){const formBox=node('section','','editor-item');formBox.append(node('h3',kind==='inquiry'?'Customer service form':'Candidate application form'));const f=content.forms[kind];for(const key of ['heading','intro','submit','confirmation','consent'])inputCard(formBox,f,key);for(const[name,field]of Object.entries(f.fields)){const row=node('fieldset','','editor-field');row.append(node('legend',name));for(const key of ['label','enabled','required'])inputCard(row,field,key,['name','phone','email'].includes(name)&&key!=='label');formBox.append(row);}const extras=node('div');extras.append(node('h3','Additional fields'));arrayEditor(extras,f.extras,()=>({id:crypto.randomUUID().slice(0,8),label:'New field',type:'text',required:false,enabled:true}),'Field',12);formBox.append(extras);box.append(formBox);}}
 else if(collectionDefaults[section]){if(!['services','trust'].includes(section))box.append(node('p','Draft and Closed entries stay hidden. Select Published when the details are complete and ready for visitors.'));arrayEditor(box,content[section],collectionDefaults[section],{services:'Service',trust:'Point',jobs:'Vacancy',projects:'Project',testimonials:'Testimonial',certifications:'Certification',announcements:'Announcement'}[section],section==='services'?12:section==='trust'?6:50);}
 else{const map={buttons:['customerButton','candidateButton'],whatsapp:['whatsappCountryCode','whatsappNumber','whatsappCustomerMessage','whatsappCandidateMessage'],social:['instagram','facebook','linkedin','tiktok','youtube','otherSocialLabel','otherSocialUrl'],banner:['bannerEnabled','bannerText','bannerImage','bannerImageAlt'],footer:['footerText','footerCopyright']};if(section==='whatsapp')box.append(node('p','Buttons stay hidden until both the country code and number are valid. Customer and candidate buttons use their own messages.'));if(section==='social')box.append(node('p','Leave a link empty to hide it. Use a full https:// link.'));for(const key of map[section]||[])inputCard(box,content.settings,key);}
 if(section==='jobs')for(const key of ['jobsHeading','jobsEmpty'])inputCard(box,content.settings,key);if(section==='testimonials')inputCard(box,content.settings,'testimonialHeading');if(section==='certifications')inputCard(box,content.settings,'certificationHeading');if(section==='announcements')inputCard(box,content.settings,'announcementHeading');}
for(const[key,label]of groups){const button=node('button',label);button.type='button';button.dataset.section=key;button.addEventListener('click',()=>{section=key;render();panel.scrollIntoView({block:'start'});});tabs.append(button);}
form.addEventListener('submit',async event=>{event.preventDefault();if(busy||uploads){message('Wait for the upload or save to finish.',true);return;}busy=true;const button=form.querySelector('[type=submit]');button.disabled=true;message('Saving changes…');try{const response=await fetch('/api/admin/content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,revision})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Changes could not be saved.');content=data.content;revision=data.revision;dirty=false;message('Saved. Your published entries and page changes are now on the website.');render();}catch(e){message(e.message+' Your edits remain in this editor.',true);}finally{busy=false;button.disabled=false;}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
async function load(){try{const response=await fetch('/api/admin/content');const data=await response.json();if(!response.ok)throw new Error(data.error||'Editor unavailable.');content=data.content;revision=data.revision;form.hidden=false;message('Owner access confirmed. Changes appear when you save.');render();}catch(e){message(e.message,true);}}
load();
